### ISSUE TITLE
pillow dependency on stretch-lite

### ISSUE THREAD

**Issue by Lewiscowles1986** [pimoroni/inky-phat#14]
So I just set up a new stretch-lite build and it looks like pillow doesn't compile just leaving to pip. This means python2 users on stretch-lite couldn't easily get setup with the inky-phat.

`sudo apt-get install python-pip python-dev python python-pillow` instead of `sudo apt-get install python-pip python-dev python` or the documented from `README.md` works perfectly and then the `sudo pip install inkyphat` works too.

Happy to submit a pr if you think this will be helpful

**Comment by Gadgetoid** [comment]
I can't recall why we favoured the pip version in this case, but I suspect it would be related to Jessie including an older version of python-pillow that was missing features that Inky pHAT needed.

The curious thing is- pip should be installing using wheels now, rather than attempting to build from source. I'm guessing it was a Python 2.7 version it was attempting to compile? Glancing over the Wheels repository suggests there are no 2.7 wheels for Pillow yet: https://www.piwheels.hostedpi.com/simple/pillow/

This makes things a little tricky, since I suspect we've got a mix of different distributions with different Pillow versions, and different Python versions that may or may not have binary wheels. *sigh*

I'm not sure what the solution should be here.

**Comment by Gadgetoid** [comment]
Looks like you're entirely right- our one-line-installer favours the apt packages and will install `python-pil` and `python-numpy` for Python 2, and `python3-pil` and `python-numpy` for Python 3.

I'll get these added to the README!

**Comment by Gadgetoid** [comment]
D'oh! Actually the obvious answer is just to `sudo apt install python-inkyphat` since it, and its dependencies, are all available from there! Have updated readme accordingly.

**Comment by Lewiscowles1986** [comment]
Just quickly, I'm pretty sure the dev instructions should be the python deps. It seems more focused on building from source, and any changes.
