### ISSUE TITLE
Allow for arbitrary rotation

### ISSUE THREAD

**Issue by Lewiscowles1986** [pimoroni/inky-phat#15]
Seems to me that the PIL library could handle rotation in software, rather than simply mirror display for 0 or 180 degrees

```python
r = r % 360
# Cannot remember if PIL rotate mutates image
set_image(
    get_image().rotate(r))
```

would have allowed for arbitrary rotation.

~~I understand that 90 degrees and 270 degrees change image dimensions without asking, but feel transposing the result over the initial image might help mitigate this.~~ (If this removed sentence is true, switch to `pillow` from `PIL`)

**Comment by Gadgetoid** [comment]
See my response here: https://github.com/pimoroni/inky-phat/pull/16

The `v_flip` and `h_flip` are also actually used for partial updates by the v1 Inky pHAT:

https://github.com/pimoroni/inky-phat/blob/64af2939e587140bfac0240d933212f971273993/library/inkyphat/inky212x104.py#L280-L327

Since the v2 Inky pHAT doesn't support partial updates (they weren't especially useful anyway) there's no-doubt a tidier way to do things now, but for the time being we're a little saddled by the need for legacy support.

**Comment by Lewiscowles1986** [comment]
Sorry, my point was that you wouldn't need 294-304, which makes multiple method signatures much shorter, reduces in-library responsibilities. The process is completely non-destructive as it works on changing the buffer image, not the files or any PIL image objects the user has access to, and the user would still have access to the parts they composited the original piece from.
