### ISSUE TITLE
Error with V1 Inkyphat

### ISSUE THREAD

**Issue by Godzil** [pimoroni/inky-phat#19]
Because of this line:

https://github.com/pimoroni/inky-phat/blob/61dcd474277bd2aeacbb17596710668460342255/examples/logo.py#L8

The app crash on a "ValueError: V1 is only available in Red"

In fact even changing to "red" it makes it to crash.

In fact on V1 the call to "set_colour" always make it to stop on the call. Maybe not throwing an error in case of a V1 when asking for red would be a better approach?

**Comment by theprotector** [comment]
I was also trying to setup my v1 Red/Black inkyphat last night and was getting the same errors. I did briefly try editing the referred to libraries, to no avail. As it was late I stopped, will be trying again tonight (hopefully).

**Comment by crashmeplease** [comment]
I have just tried my Raspi 1 B+ (4.14.62+) and I have this error on all of the examples. Installed ok with no errors, rebooted afterwards.. However the inky phat does work on my Raspi 3. Ideas how to fix this?

**Comment by thn80** [comment]
After a nice talk to the Pimoroni team we could solve the problem.

The problem on my system was that "apt" installed v1.0.0 of the library. Since upgrading inkyphat library to 1.0.1 it works like a charm.
`sudo apt remove python-inkyphat`
`sudo pip install inkyphat==1.0.1`

It is also a good idea to get the latest examples from Github.
