### ISSUE TITLE
How do I rotate text?

### ISSUE THREAD

**Issue by r0ckarong** [pimoroni/inky-phat#3]
I managed to create a box on the display using some ImageDraw stuff but I can't figure out how to write text to it (at least so that it is visible). I can print text fine using the inkyphat libs but that only allows me to place it in one way.

From what I have read in PIL/Pillow you should be able to create a temp image, write text to it, rotate the temp image and paste it into the inkyphat. 

I can't figure out how to do this. 

* How do I create a new temporary image area to draw to?
* How do I write text with the inkyphat fonts and colors into this temp area?
* How do I rotate it (90 degrees)?
* How do I paste this temp image into the inkyphat buffer that I've build with my other commands?

Can we have a simple function/method that allows rotating text? I would be happy for pointers of what I'm doing wrong with PIL to maybe understand what to do and add something here.

I want to rotate this temperature text and use the same functionality to label the scale.

![2017-07-07 21 04 05](https://user-images.githubusercontent.com/4920542/27972793-e1258994-6357-11e7-8dbf-fb429a0b035b.jpg)

**Comment by Gadgetoid** [comment]
I was torn between simple, and just exposing PIL/Pillow to encourage users to pick up some transferable skills. I fully intend, of course, to back up said encouragement with some help!

In your case, it would probably be easier to manipulate everything as a PIL image that's HEIGHT/WIDTH in shape, and then rotate it 90degrees before pasting it onto Inky pHAT. 

But let's look at rotating text since it gives you more flexibility- specially if you want to do anything like rotate text to 45 degrees, etc:

```
text = "29.5"
font = ImageFont.truetype(inkyphat.fonts.AmaticSCBold, 38)

# Get the width/height of the text if it were rendered with our chosen font
text_w, text_h = font.getsize(text)

# Create a 1bit mask canvas to fit the text
text_mask = inkyphat.Image.new("1", (text_w, text_h))

# Set up ImageDraw
mask_draw = inkyphat.ImageDraw.Draw(text_mask)

# Write the text, using colour 1 (on) as this is an on/off 1bit canvas
mask_draw.text((0, 0), text, 1, font)

# Using the mask to guide which pixels should be set, 
# this is where we pick the text colour.
inkyphat.paste(inkyphat.BLACK, (0, 0), text_mask.rotate(90))
```

Note: the reason why I create what's effectively a *mask* rather than an image is because it allows us to paste the newly drawn text over the top of Inky pHATs image buffer with transparency using the `paste` method's build-in support for taking a colour, and an image mask.

Masking like this is super useful for compositing stuff together in Inky pHAT but a mask *must* be a 1bit-per-pixel image where 1 indicates pixels that should be set, and 0 indicates pixels that should be ignored.

Here's a really crude function embedded in a quick demo script for drawing text at a given position and rotation. It's far from accurate with positioning, but it gets the job done:

```
#!/usr/bin/env python

import inkyphat

def draw_text(position, text, font=None, colour=inkyphat.BLACK, rotation=0):
    x, y = position
    if font is None:
        font = inkyphat.ImageFont.truetype(inkyphat.fonts.PressStart2P,12)
    w, h = font.getsize(text)
    mask = inkyphat.Image.new('1', (w, h))
    draw = inkyphat.ImageDraw.Draw(mask)
    draw.text((0, 0), text, 1, font)
    mask = mask.rotate(rotation, expand=True)
    inkyphat.paste(colour, position, mask)

draw_text((20, 20), "Hello", colour=inkyphat.RED, rotation=45)
draw_text((80, 20), "World", rotation=90)

inkyphat.show()
```

**Comment by r0ckarong** [comment]
Thank you so much. I will try this as soon as my replacement inky arrives.

**Comment by france193** [comment]
Sorry, can you explain me hot to write text using classic import:

from inky import InkyPHAT
from PIL import Image, ImageFont, ImageDraw
from font_fredoka_one import FredokaOne
?

I try your Example, but I do not understand how to rotate the code because i cannot find all Methods on those librarie...

**Comment by Gadgetoid** [comment]
The new `inky` library removes all PIL functions, so as not to obfuscate the use of the Pillow/PIL library.

You should be using PIL directly.

See: https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html

And: https://pillow.readthedocs.io/en/stable/reference/Image.html
