### ISSUE TITLE
Palette Inky-pHAT.gpl has #feffff for white

### ISSUE THREAD

**Issue by scruss** [pimoroni/inky-phat#7]
Palette file contains

    GIMP Palette
    Name: Inky pHAT
    Columns: 1
    #
    254 255 255	Untitled
      0   0   0	Untitled
    255   0   0	Untitled

but images in examples have the following colour map (identified by ImageMagick):

      Colormap:
             0: (255,255,255) #FFFFFF white
             1: (  0,  0,  0) #000000 black
             2: (255,  0,  0) #FF0000 red

Rendering an image with the #ffffff colormap using `inkyphat.set_image(Image.open(…))` seems to work as well as using the official #feffff one.

**Comment by Gadgetoid** [comment]
Good spot. I wonder how that happened.

Inky pHAT doesn't really care what colours are actually in the palette, since it operates by index only and irrespective of what colour is where it will always treat 0 as white, 1 as black and 2 as red.

Where it counts is when you switch your image to Indexed Palette mode in GIMP. At this point it will snap all of the colours in the image to the nearest available colour in the palette. This small variance will have no effect.

You can actually exploit this effect- if your image is predominately yellow, blue and green for example you can create a 3-colour palette with picks from those colours, the order of your palette will control which colour then gets treated as White/Black/Red on Inky pHAT.

**Comment by scruss** [comment]
Good to know! I'll close this up and submit a patch (or whatever the young 'uns call it today)
