### ISSUE TITLE
image always rendered with colours inverted

### ISSUE THREAD

**Issue by jose1711** [pimoroni/inky-phat#8]
hello,

no matter what i do, i always get the colours in the attached image inverted (black background instead of white). can someone please help (i used ```logo.py``` from the examples section)? thank you, j
![example](https://user-images.githubusercontent.com/1406222/28272167-f1f01ff4-6b0a-11e7-8d92-376f766b7fbf.png)

**Comment by Gadgetoid** [comment]
How did you prepare your image? You have to pay close attention to the order of the colour palette when exporting- which is frustrating. Photoshop's new export functionality, for example, will totally mess it up, whereas the legacy "Save For Web" does not. D'oh!

I'll have to see if there's a way to fix the colour palettes in these images. I guess it should be simple enough to have a script that opens it, performs a palette swap based on parameters, and saves the result.

**Comment by jose1711** [comment]
i tried to follow the instructions (use gimp + custom palette file). i guess i did something wrong. anyway in the end i solved it like this:
```
img = Image.open('img.png')
img2 = Image.new(mode='P', size=(212, 104))
remapped = []
pxmap = {0: 2, 1:0, 2:1}
for px in img.getdata():
    remapped.append(pxmap[px])
img2.putdata(remapped)
inkyphat.set_image(img2)
inkyphat.show()
```
i guess this can either be closed or flagged as enhancement. having a separate method implementing color indexes rotation would be nice i guess.

**Comment by Gadgetoid** [comment]
I'd tend to agree a method that supports colour index rotation would be nice. I'd maybe override `set_image` with an optional argument `map` or `colswap` or something.

**Comment by shackiey** [comment]
Hi - I just encountered this issue myself, and was very pleased to see this mapping fix implemented. However, I dug a little deeper into Gimp to find why this was happening with images I prepared. Turns out when the inkyphat palette is imported into Gimp, it is re-ordering the colours so that they are not in the expected order White,Black,Red. Simply opening the colourmap window & re-arranging the colours into the required order has fixed it for me, without using the mapping feature above.

**Comment by marcosikkens** [comment]
I experienced this problem also, it was fixed by shackiey's comment. However it also needs to be updated in the documentation at: https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-inky-phat.

There it also states the colour order in "White,Black,Red" en "Black,white, red" in the same page which only confused me.
